package io.laudoak.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

/**
 * generated by SQL2Q
 * on Thu Jan 05 18:24:25 CST 2017
 */

@Builder
@AllArgsConstructor
@NoArgsConstructor
@Data
public class Blog //博客表
{
        private Long id; //主键
        private String title; //标题
        private String content; //正文
        private Long ownerId; //作者ID
        private Byte recommend; //是否被推荐
        private Date createdAt; //创建时间
        private Date updatedAt; //更新时间
    
}
