package io.laudoak.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

/**
 * generated by SQL2Q
 * on Thu Jan 05 18:24:25 CST 2017
 */

@Builder
@AllArgsConstructor
@NoArgsConstructor
@Data
public class Comment //评论表
{
        private Long id; //主键
        private String content; //评论内容
        private Long blogId; //评论的博客ID
        private Long ownerId; //评论作者
        private Date createdAt; //创建时间
        private Date updatedAt; //更新时间
    
}
