package io.laudoak.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

/**
 * generated by SQL2Q
 * on Thu Jan 05 18:24:25 CST 2017
 */

@Builder
@AllArgsConstructor
@NoArgsConstructor
@Data
public class Gallery //画廊表
{
        private Long id; //主键
        private String name; //画廊名称
        private Long ownerId; //画廊作者ID
        private Date createdAt; //创建时间
        private Date updatedAt; //更新时间
    
}
