package io.laudoak.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

/**
 * generated by SQL2Q
 * on Thu Jan 05 19:26:03 CST 2017
 */

@Builder
@AllArgsConstructor
@NoArgsConstructor
@Data
public class Member //会员表
{
        private Long id; //主键
        private String nick; //昵称
        private String pwd; //密码
        private String avatar; //头像路径
        private Long groupId; //会员组ID
        private Date createdAt; //创建时间
        private Date updatedAt; //更新时间
    
}
