package io.laudoak.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

/**
 * generated by SQL2Q
 * on Thu Jan 05 19:26:03 CST 2017
 */

@Builder
@AllArgsConstructor
@NoArgsConstructor
@Data
public class Notification //通知表
{
        private Long id; //主键
        private String title; //通知标题
        private String content; //通知正文
        private Long ownerId; //发布通知的管理员ID
        private Date createdAt; //创建时间
        private Date updatedAt; //更新时间
    
}
