package io.laudoak.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

/**
 * generated by SQL2Q
 * on Thu Jan 05 19:26:03 CST 2017
 */

@Builder
@AllArgsConstructor
@NoArgsConstructor
@Data
public class PointDetail //积分明细表
{
        private Long id; //主键
        private Long ownerId; //产生积分的会员ID
        private Integer amount; //产生的积分数量
        private Long pointGroupId; //所属会员组ID
        private Date createdAt; //创建时间
        private Date updatedAt; //更新时间
    
}
