package io.laudoak.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

/**
 * generated by SQL2Q
 * on Thu Jan 05 18:24:25 CST 2017
 */

@Builder
@AllArgsConstructor
@NoArgsConstructor
@Data
public class PointGroup //积分组表
{
        private Long id; //主键
        private String name; //积分组名称
        private String actionName; //积分组动作名称
        private String actionCode; //积分组动作码
        private Integer amount; //积分组规定积分数
        private Date createdAt; //创建时间
        private Date updatedAt; //更新时间
    
}
