package io.laudoak.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

/**
 * generated by SQL2Q
 * on Thu Jan 05 19:26:03 CST 2017
 */

@Builder
@AllArgsConstructor
@NoArgsConstructor
@Data
public class SensitiveWord //敏感词表
{
        private Long id; //主键
        private String word; //敏感词
        private Date createdAt; //创建时间
        private Date updatedAt; //更新时间
    
}
