package io.laudoak.service;

import io.laudoak.model.AdminGroup;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 18:24:25 CST 2017
 */
public interface AdminGroupService
{
    Integer insert(AdminGroup adminGroup);

    Integer delete(AdminGroup adminGroup);

    Integer update(AdminGroup adminGroup);

    AdminGroup selectOne(Long id);

    List<AdminGroup> select();

    Long count();

}
