package io.laudoak.service;

import io.laudoak.model.Admin;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 18:24:25 CST 2017
 */
public interface AdminService
{
    Integer insert(Admin admin);

    Integer delete(Admin admin);

    Integer update(Admin admin);

    Admin selectOne(Long id);

    List<Admin> select();

    Long count();

}
