package io.laudoak.service;

import io.laudoak.model.Blog;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 19:26:03 CST 2017
 */
public interface BlogService
{
    Integer insert(Blog blog);

    Integer delete(Blog blog);

    Integer update(Blog blog);

    Blog selectOne(Long id);

    List<Blog> select();

    Long count();

}
