package io.laudoak.service;

import io.laudoak.model.Comment;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 19:26:03 CST 2017
 */
public interface CommentService
{
    Integer insert(Comment comment);

    Integer delete(Comment comment);

    Integer update(Comment comment);

    Comment selectOne(Long id);

    List<Comment> select();

    Long count();

}
