package io.laudoak.service;

import io.laudoak.model.Gallery;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 19:26:03 CST 2017
 */
public interface GalleryService
{
    Integer insert(Gallery gallery);

    Integer delete(Gallery gallery);

    Integer update(Gallery gallery);

    Gallery selectOne(Long id);

    List<Gallery> select();

    Long count();

}
