package io.laudoak.service;

import io.laudoak.model.MemberGroup;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 18:24:25 CST 2017
 */
public interface MemberGroupService
{
    Integer insert(MemberGroup memberGroup);

    Integer delete(MemberGroup memberGroup);

    Integer update(MemberGroup memberGroup);

    MemberGroup selectOne(Long id);

    List<MemberGroup> select();

    Long count();

}
