package io.laudoak.service;

import io.laudoak.model.Member;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 19:26:03 CST 2017
 */
public interface MemberService
{
    Integer insert(Member member);

    Integer delete(Member member);

    Integer update(Member member);

    Member selectOne(Long id);

    List<Member> select();

    Long count();

}
