package io.laudoak.service;

import io.laudoak.model.Notification;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 19:26:03 CST 2017
 */
public interface NotificationService
{
    Integer insert(Notification notification);

    Integer delete(Notification notification);

    Integer update(Notification notification);

    Notification selectOne(Long id);

    List<Notification> select();

    Long count();

}
