package io.laudoak.service;

import io.laudoak.model.PointDetail;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 19:26:03 CST 2017
 */
public interface PointDetailService
{
    Integer insert(PointDetail pointDetail);

    Integer delete(PointDetail pointDetail);

    Integer update(PointDetail pointDetail);

    PointDetail selectOne(Long id);

    List<PointDetail> select();

    Long count();

}
