package io.laudoak.service;

import io.laudoak.model.PointGroup;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 18:24:25 CST 2017
 */
public interface PointGroupService
{
    Integer insert(PointGroup pointGroup);

    Integer delete(PointGroup pointGroup);

    Integer update(PointGroup pointGroup);

    PointGroup selectOne(Long id);

    List<PointGroup> select();

    Long count();

}
