package io.laudoak.service;

import io.laudoak.model.SensitiveWord;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 19:26:03 CST 2017
 */
public interface SensitiveWordService
{
    Integer insert(SensitiveWord sensitiveWord);

    Integer delete(SensitiveWord sensitiveWord);

    Integer update(SensitiveWord sensitiveWord);

    SensitiveWord selectOne(Long id);

    List<SensitiveWord> select();

    Long count();

}
