package io.laudoak.service.impl;


import io.laudoak.dao.AdminDao;
import io.laudoak.model.Admin;
import io.laudoak.service.AdminService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 19:26:03 CST 2017
 */

@Service
public class AdminServiceImpl implements AdminService
{

    @Autowired
    private AdminDao dao;

    @Override
    public Integer insert(Admin admin)
    {
        return dao.insert(admin);
    }

    @Override
    public Integer delete(Admin admin)
    {
        return dao.delete(admin);
    }

    @Override
    public Integer update(Admin admin)
    {
        return dao.update(admin);
    }

    @Override
    public Admin selectOne(Long id)
    {
        return dao.selectOne(id);
    }

    @Override
    public List<Admin> select()
    {
        return dao.select();
    }

    @Override
    public Long count()
    {
        return dao.count();
    }

}
