package io.laudoak.service.impl;


import io.laudoak.dao.AdminGroupDao;
import io.laudoak.model.AdminGroup;
import io.laudoak.service.AdminGroupService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 19:26:03 CST 2017
 */

@Service
public class AdminGroupServiceImpl implements AdminGroupService
{

    @Autowired
    private AdminGroupDao dao;

    @Override
    public Integer insert(AdminGroup adminGroup)
    {
        return dao.insert(adminGroup);
    }

    @Override
    public Integer delete(AdminGroup adminGroup)
    {
        return dao.delete(adminGroup);
    }

    @Override
    public Integer update(AdminGroup adminGroup)
    {
        return dao.update(adminGroup);
    }

    @Override
    public AdminGroup selectOne(Long id)
    {
        return dao.selectOne(id);
    }

    @Override
    public List<AdminGroup> select()
    {
        return dao.select();
    }

    @Override
    public Long count()
    {
        return dao.count();
    }

}
