package io.laudoak.service.impl;


import io.laudoak.dao.BlogDao;
import io.laudoak.model.Blog;
import io.laudoak.service.BlogService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 18:24:25 CST 2017
 */

@Service
public class BlogServiceImpl implements BlogService
{

    @Autowired
    private BlogDao dao;

    @Override
    public Integer insert(Blog blog)
    {
        return dao.insert(blog);
    }

    @Override
    public Integer delete(Blog blog)
    {
        return dao.delete(blog);
    }

    @Override
    public Integer update(Blog blog)
    {
        return dao.update(blog);
    }

    @Override
    public Blog selectOne(Long id)
    {
        return dao.selectOne(id);
    }

    @Override
    public List<Blog> select()
    {
        return dao.select();
    }

    @Override
    public Long count()
    {
        return dao.count();
    }

}
