package io.laudoak.service.impl;


import io.laudoak.dao.CommentDao;
import io.laudoak.model.Comment;
import io.laudoak.service.CommentService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 19:26:03 CST 2017
 */

@Service
public class CommentServiceImpl implements CommentService
{

    @Autowired
    private CommentDao dao;

    @Override
    public Integer insert(Comment comment)
    {
        return dao.insert(comment);
    }

    @Override
    public Integer delete(Comment comment)
    {
        return dao.delete(comment);
    }

    @Override
    public Integer update(Comment comment)
    {
        return dao.update(comment);
    }

    @Override
    public Comment selectOne(Long id)
    {
        return dao.selectOne(id);
    }

    @Override
    public List<Comment> select()
    {
        return dao.select();
    }

    @Override
    public Long count()
    {
        return dao.count();
    }

}
