package io.laudoak.service.impl;


import io.laudoak.dao.GalleryDao;
import io.laudoak.model.Gallery;
import io.laudoak.service.GalleryService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 18:24:25 CST 2017
 */

@Service
public class GalleryServiceImpl implements GalleryService
{

    @Autowired
    private GalleryDao dao;

    @Override
    public Integer insert(Gallery gallery)
    {
        return dao.insert(gallery);
    }

    @Override
    public Integer delete(Gallery gallery)
    {
        return dao.delete(gallery);
    }

    @Override
    public Integer update(Gallery gallery)
    {
        return dao.update(gallery);
    }

    @Override
    public Gallery selectOne(Long id)
    {
        return dao.selectOne(id);
    }

    @Override
    public List<Gallery> select()
    {
        return dao.select();
    }

    @Override
    public Long count()
    {
        return dao.count();
    }

}
