package io.laudoak.service.impl;


import io.laudoak.dao.MemberDao;
import io.laudoak.model.Member;
import io.laudoak.service.MemberService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 18:24:25 CST 2017
 */

@Service
public class MemberServiceImpl implements MemberService
{

    @Autowired
    private MemberDao dao;

    @Override
    public Integer insert(Member member)
    {
        return dao.insert(member);
    }

    @Override
    public Integer delete(Member member)
    {
        return dao.delete(member);
    }

    @Override
    public Integer update(Member member)
    {
        return dao.update(member);
    }

    @Override
    public Member selectOne(Long id)
    {
        return dao.selectOne(id);
    }

    @Override
    public List<Member> select()
    {
        return dao.select();
    }

    @Override
    public Long count()
    {
        return dao.count();
    }

}
