package io.laudoak.service.impl;


import io.laudoak.dao.NotificationDao;
import io.laudoak.model.Notification;
import io.laudoak.service.NotificationService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 18:24:25 CST 2017
 */

@Service
public class NotificationServiceImpl implements NotificationService
{

    @Autowired
    private NotificationDao dao;

    @Override
    public Integer insert(Notification notification)
    {
        return dao.insert(notification);
    }

    @Override
    public Integer delete(Notification notification)
    {
        return dao.delete(notification);
    }

    @Override
    public Integer update(Notification notification)
    {
        return dao.update(notification);
    }

    @Override
    public Notification selectOne(Long id)
    {
        return dao.selectOne(id);
    }

    @Override
    public List<Notification> select()
    {
        return dao.select();
    }

    @Override
    public Long count()
    {
        return dao.count();
    }

}
