package io.laudoak.service.impl;


import io.laudoak.dao.PictureDao;
import io.laudoak.model.Picture;
import io.laudoak.service.PictureService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 18:24:25 CST 2017
 */

@Service
public class PictureServiceImpl implements PictureService
{

    @Autowired
    private PictureDao dao;

    @Override
    public Integer insert(Picture picture)
    {
        return dao.insert(picture);
    }

    @Override
    public Integer delete(Picture picture)
    {
        return dao.delete(picture);
    }

    @Override
    public Integer update(Picture picture)
    {
        return dao.update(picture);
    }

    @Override
    public Picture selectOne(Long id)
    {
        return dao.selectOne(id);
    }

    @Override
    public List<Picture> select()
    {
        return dao.select();
    }

    @Override
    public Long count()
    {
        return dao.count();
    }

}
