package io.laudoak.service.impl;


import io.laudoak.dao.PointDetailDao;
import io.laudoak.model.PointDetail;
import io.laudoak.service.PointDetailService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * generated by SQL2Q
 * on Thu Jan 05 19:26:03 CST 2017
 */

@Service
public class PointDetailServiceImpl implements PointDetailService
{

    @Autowired
    private PointDetailDao dao;

    @Override
    public Integer insert(PointDetail pointDetail)
    {
        return dao.insert(pointDetail);
    }

    @Override
    public Integer delete(PointDetail pointDetail)
    {
        return dao.delete(pointDetail);
    }

    @Override
    public Integer update(PointDetail pointDetail)
    {
        return dao.update(pointDetail);
    }

    @Override
    public PointDetail selectOne(Long id)
    {
        return dao.selectOne(id);
    }

    @Override
    public List<PointDetail> select()
    {
        return dao.select();
    }

    @Override
    public Long count()
    {
        return dao.count();
    }

}
