package io.laudoak.dao;

import io.laudoak.model.MemberGroup;
import org.springframework.stereotype.Repository;

/**
 * generated by SQL2O
 * on Thu Jan 05 19:26:03 CST 2017
 */
@Repository
public class MemberGroupDao extends Dao<MemberGroup>
{
}
