package io.laudoak.dao;

import io.laudoak.model.SensitiveWord;
import org.springframework.stereotype.Repository;

/**
 * generated by SQL2O
 * on Thu Jan 05 18:24:25 CST 2017
 */
@Repository
public class SensitiveWordDao extends Dao<SensitiveWord>
{
}
